# Generated by Django 3.2.3 on 2021-05-30 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='warriorpost',
            name='title',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='warriorpost',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
