# Generated by Django 3.2.3 on 2021-05-30 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210530_1421'),
    ]

    operations = [
        migrations.RenameField(
            model_name='warriorpost',
            old_name='created',
            new_name='date_scraped',
        ),
        migrations.RemoveField(
            model_name='warriorpost',
            name='updated',
        ),
        migrations.AddField(
            model_name='warriorpost',
            name='date_posted',
            field=models.DateTimeField(null=True),
        ),
    ]
